discordToken: 'Discord Token'
guildID: 'Discord Guild ID'
clientID: 'Application ID'
groupMeChannelID: 'Channel for GroupMe'
port: 3000
groupMeID: 'GroupMe bot id'
groupMeAccessToken: 'GroupMe access token'
groupMeWebhook: 'Webhook for the GroupMe channel'
gapiKey: 'Google API Key'